series: Basic C++
title: N Dimensional Arrays
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Use arrays to store multiple dimensional data.
language: C++
tags:
  - Core
extra_resources:
connections:
  - series: Basic C++
    title: Arrays